openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8889'
    description: Generated server url
paths:
  /stwitter:
    get:
      tags:
        - stwitter-controller
      operationId: getAllPosts
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostViewModel'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CustomErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/CustomErrorResponse'
    post:
      tags:
        - stwitter-controller
      operationId: createPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostViewModel'
        required: true
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Post'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CustomErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/CustomErrorResponse'
  '/stwitter/{id}':
    get:
      tags:
        - stwitter-controller
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PostViewModel'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CustomErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/CustomErrorResponse'
  '/stwitter/user/{posterName}':
    get:
      tags:
        - stwitter-controller
      operationId: getPostByPoster
      parameters:
        - name: posterName
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PostViewModel'
        '422':
          description: Unprocessable Entity
          content:
            '*/*':
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CustomErrorResponse'
                  - type: array
                    items:
                      $ref: '#/components/schemas/CustomErrorResponse'
components:
  schemas:
    CustomErrorResponse:
      type: object
      properties:
        errorMsg:
          type: string
        status:
          type: integer
          format: int32
        errorCode:
          type: string
        timestamp:
          type: string
          format: date-time
    Comment:
      type: object
      properties:
        commentId:
          type: integer
          format: int32
        postId:
          type: integer
          format: int32
        createDate:
          type: string
          format: date
        commenterName:
          type: string
        comment:
          type: string
    PostViewModel:
      required:
        - postDate
        - posterName
      type: object
      properties:
        postId:
          type: integer
          format: int32
        postDate:
          type: string
          format: date
        posterName:
          maxLength: 50
          minLength: 0
          type: string
        post:
          maxLength: 255
          minLength: 0
          type: string
        commentList:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
    Post:
      type: object
      properties:
        postId:
          type: integer
          format: int32
        postDate:
          type: string
          format: date
        posterName:
          type: string
        post:
          type: string
